# Generated by Django 2.2.6 on 2020-05-12 06:49

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('zaratamap_app', '0002_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='street',
            name='rectangle_borders',
            field=jsonfield.fields.JSONField(default='[]'),
            preserve_default=False,
        ),
    ]
