# Generated by Django 2.2.6 on 2020-05-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaratamap_app', '0004_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='date_from',
            field=models.DateField(null=True),
        ),
    ]
