# Generated by Django 2.2.6 on 2020-05-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaratamap_app', '0005_auto_20200513_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='above_max_day',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='above_max_night',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='km_dec',
            field=models.DecimalField(blank=True, decimal_places=1000, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='km_int',
            field=models.DecimalField(blank=True, decimal_places=1000, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='lat_dec',
            field=models.DecimalField(blank=True, decimal_places=1000, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='lat_int',
            field=models.DecimalField(blank=True, decimal_places=1000, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='lon_dec',
            field=models.DecimalField(blank=True, decimal_places=1000, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='lon_int',
            field=models.DecimalField(blank=True, decimal_places=1000, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='noise_from',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='noise_to',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='streetName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='time_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='time_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
