# Generated by Django 2.2.6 on 2020-05-14 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaratamap_app', '0008_filter_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='user',
        ),
    ]
