# Generated by Django 2.2.6 on 2020-05-18 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zaratamap_app', '0010_filter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='filter_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
