# Generated by Django 2.2.6 on 2020-05-31 07:04

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('zaratamap_app', '0011_filter_filter_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('rectangle_borders', jsonfield.fields.JSONField()),
            ],
        ),
    ]
