# Generated by Django 2.2.6 on 2020-05-31 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zaratamap_app', '0012_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='street',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zaratamap_app.City'),
            preserve_default=False,
        ),
    ]
