# Generated by Django 2.2.6 on 2020-06-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaratamap_app', '0016_auto_20200604_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='rectangle_lower_lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='rectangle_lower_lon',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='rectangle_upper_lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='rectangle_upper_lon',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
